apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-demo-tls
  namespace: nginx-demo
spec:
  secretName: nginx-demo-tls
  duration: 2160h
  renewBefore: 360h
  commonName: demo.example.com
  dnsNames:
    - demo.example.com
  issuerRef:
    name: nginx-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
